package(
    default_applicable_licenses = ["//third_party/odml:license"],
    default_visibility = [
        "//:internal",
    ],
)

licenses(["notice"])

exports_files([
    "model.task",
    "lora_gpu_rank16.tflite",
])
